# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('X', models.IntegerField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Direction', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('Alive', models.BooleanField(default=True)),
            ],
        ),
    ]
