# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-14 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooting_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.IntegerField(default=0),
        ),
    ]
